name: Reporte Energético Diario

on:
  schedule:
    # 13:00 UTC corresponde a las 08:00 AM hora Bogotá (UTC-5)
    - cron: '0 13 * * *'
  workflow_dispatch: # Permite ejecución manual

jobs:
  ejecucion:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar dependencias
        run: |
          pip install pandas numpy matplotlib pydataxm

      - name: Ejecutar Script
        run: python script_prueba.py

      - name: Guardar Gráfica
        uses: actions/upload-artifact@v4
        with:
          name: reporte-visual
          path: reporte_energetico.png
